# Generated by Django 5.2.5 on 2025-11-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Progress Records'},
        ),
        migrations.AddField(
            model_name='progress',
            name='progress_pct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
